name: tl_cipher
description: Cryptography code used in Text Î».
version: 1.0.0
repository: https://github.com/rorokimdim/tl_cipher

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  archive: ^3.3.6
  sodium: '>=2.0.1 <2.1.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
