name: tl_cipher
description: Cryptography code used in Text Î».
version: 1.0.0
repository: https://github.com/textlambda/cipher
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.6.1
  sodium: ^3.2.0+1

dev_dependencies:
  dart_code_metrics: ^5.7.2
  lints: ^2.0.0
  test: ^1.21.0
